language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm
before_script: composer install --dev
script: php vendor/phpunit/phpunit/phpunit.php --log-tap report.tap
after_script: curl -X POST --data-binary @report.tap http://dox.rtens.org/projects/watoki-tempan/reports